---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-affinity
  labels:
    author: venky
    type: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      - type: proxy
  template:
    metadata:
      name: nginx-pod
      labels:
        type: proxy
    spec:
      containers:
        - name: mynginx
          image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: Slave1
                    operator: In
                    values:
                      - intelliqit1
                  - key: Slave3
                    operator: In
                    values:
                      - intelliqit3
...