---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    author: venky
    name: postgres
spec:
  containers:
    - name: mypostgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: venky
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: myuser
...