---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-secret
  labels:
    author: venky
    name: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres
    spec:
      containers:
        - name: mydb
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: dbname
...
