---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    author: venky
    name: appserver
spec:
  containers:
    - name: myhttpd
      image: httpd
  tolerations:
    - key: Slave1
      value: Intelliqit1
      operator: Equal
      effect: NoSchedule
...